package com.tictactec.ta.lib;

import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.ptr.IntByReference;

public interface TALib extends Library {
    TALib INSTANCE = Native.load("ta-lib", TALib.class);

    // Core functions
    int TA_Initialize();
    int TA_Shutdown();

    int TA_ACCBANDS(int startIdx, int endIdx, double[] high, double[] low, double[] close, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outRealUpperBand, double[] outRealMiddleBand, double[] outRealLowerBand);
    int TA_ACOS(int startIdx, int endIdx, double[] inreal, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_AD(int startIdx, int endIdx, double[] high, double[] low, double[] close, double[] volume, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_ADD(int startIdx, int endIdx, double[] inreal0, double[] inreal1, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_ADOSC(int startIdx, int endIdx, double[] high, double[] low, double[] close, double[] volume, int optInFastPeriod, int optInSlowPeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_ADX(int startIdx, int endIdx, double[] high, double[] low, double[] close, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_ADXR(int startIdx, int endIdx, double[] high, double[] low, double[] close, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_APO(int startIdx, int endIdx, double[] inreal, int optInFastPeriod, int optInSlowPeriod, int optInMAType, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_AROON(int startIdx, int endIdx, double[] high, double[] low, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outAroonDown, double[] outAroonUp);
    int TA_AROONOSC(int startIdx, int endIdx, double[] high, double[] low, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_ASIN(int startIdx, int endIdx, double[] inreal, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_ATAN(int startIdx, int endIdx, double[] inreal, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_ATR(int startIdx, int endIdx, double[] high, double[] low, double[] close, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_AVGPRICE(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_AVGDEV(int startIdx, int endIdx, double[] inreal, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_BBANDS(int startIdx, int endIdx, double[] inreal, int optInTimePeriod, double optInDeviationsup, double optInDeviationsdown, int optInMAType, IntByReference outBegIdx, IntByReference outNBElement, double[] outRealUpperBand, double[] outRealMiddleBand, double[] outRealLowerBand);
    int TA_BETA(int startIdx, int endIdx, double[] inreal0, double[] inreal1, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_BOP(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_CCI(int startIdx, int endIdx, double[] high, double[] low, double[] close, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_CDL2CROWS(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDL3BLACKCROWS(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDL3INSIDE(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDL3LINESTRIKE(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDL3OUTSIDE(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDL3STARSINSOUTH(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDL3WHITESOLDIERS(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLABANDONEDBABY(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, double optInPenetration, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLADVANCEBLOCK(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLBELTHOLD(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLBREAKAWAY(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLCLOSINGMARUBOZU(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLCONCEALBABYSWALL(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLCOUNTERATTACK(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLDARKCLOUDCOVER(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, double optInPenetration, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLDOJI(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLDOJISTAR(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLDRAGONFLYDOJI(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLENGULFING(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLEVENINGDOJISTAR(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, double optInPenetration, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLEVENINGSTAR(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, double optInPenetration, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLGAPSIDESIDEWHITE(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLGRAVESTONEDOJI(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLHAMMER(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLHANGINGMAN(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLHARAMI(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLHARAMICROSS(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLHIGHWAVE(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLHIKKAKE(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLHIKKAKEMOD(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLHOMINGPIGEON(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLIDENTICAL3CROWS(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLINNECK(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLINVERTEDHAMMER(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLKICKING(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLKICKINGBYLENGTH(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLLADDERBOTTOM(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLLONGLEGGEDDOJI(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLLONGLINE(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLMARUBOZU(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLMATCHINGLOW(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLMATHOLD(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, double optInPenetration, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLMORNINGDOJISTAR(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, double optInPenetration, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLMORNINGSTAR(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, double optInPenetration, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLONNECK(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLPIERCING(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLRICKSHAWMAN(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLRISEFALL3METHODS(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLSEPARATINGLINES(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLSHOOTINGSTAR(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLSHORTLINE(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLSPINNINGTOP(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLSTALLEDPATTERN(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLSTICKSANDWICH(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLTAKURI(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLTASUKIGAP(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLTHRUSTING(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLTRISTAR(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLUNIQUE3RIVER(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLUPSIDEGAP2CROWS(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CDLXSIDEGAP3METHODS(int startIdx, int endIdx, double[] open, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_CEIL(int startIdx, int endIdx, double[] inreal, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_CMO(int startIdx, int endIdx, double[] inreal, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_CORREL(int startIdx, int endIdx, double[] inreal0, double[] inreal1, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_COS(int startIdx, int endIdx, double[] inreal, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_COSH(int startIdx, int endIdx, double[] inreal, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_DEMA(int startIdx, int endIdx, double[] inreal, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_DIV(int startIdx, int endIdx, double[] inreal0, double[] inreal1, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_DX(int startIdx, int endIdx, double[] high, double[] low, double[] close, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_EMA(int startIdx, int endIdx, double[] inreal, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_EXP(int startIdx, int endIdx, double[] inreal, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_FLOOR(int startIdx, int endIdx, double[] inreal, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_HT_DCPERIOD(int startIdx, int endIdx, double[] inreal, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_HT_DCPHASE(int startIdx, int endIdx, double[] inreal, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_HT_PHASOR(int startIdx, int endIdx, double[] inreal, IntByReference outBegIdx, IntByReference outNBElement, double[] outInPhase, double[] outQuadrature);
    int TA_HT_SINE(int startIdx, int endIdx, double[] inreal, IntByReference outBegIdx, IntByReference outNBElement, double[] outSine, double[] outLeadSine);
    int TA_HT_TRENDLINE(int startIdx, int endIdx, double[] inreal, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_HT_TRENDMODE(int startIdx, int endIdx, double[] inreal, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_IMI(int startIdx, int endIdx, double[] open, double[] close, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_KAMA(int startIdx, int endIdx, double[] inreal, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_LINEARREG(int startIdx, int endIdx, double[] inreal, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_LINEARREG_ANGLE(int startIdx, int endIdx, double[] inreal, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_LINEARREG_INTERCEPT(int startIdx, int endIdx, double[] inreal, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_LINEARREG_SLOPE(int startIdx, int endIdx, double[] inreal, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_LN(int startIdx, int endIdx, double[] inreal, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_LOG10(int startIdx, int endIdx, double[] inreal, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_MA(int startIdx, int endIdx, double[] inreal, int optInTimePeriod, int optInMAType, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_MACD(int startIdx, int endIdx, double[] inreal, int optInFastPeriod, int optInSlowPeriod, int optInSignalPeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outMACD, double[] outMACDSignal, double[] outMACDHist);
    int TA_MACDEXT(int startIdx, int endIdx, double[] inreal, int optInFastPeriod, int optInFastMA, int optInSlowPeriod, int optInSlowMA, int optInSignalPeriod, int optInSignalMA, IntByReference outBegIdx, IntByReference outNBElement, double[] outMACD, double[] outMACDSignal, double[] outMACDHist);
    int TA_MACDFIX(int startIdx, int endIdx, double[] inreal, int optInSignalPeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outMACD, double[] outMACDSignal, double[] outMACDHist);
    int TA_MAMA(int startIdx, int endIdx, double[] inreal, double optInFastLimit, double optInSlowLimit, IntByReference outBegIdx, IntByReference outNBElement, double[] outMAMA, double[] outFAMA);
    int TA_MAVP(int startIdx, int endIdx, double[] inreal, double[] inperiods, int optInMinimumPeriod, int optInMaximumPeriod, int optInMAType, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_MAX(int startIdx, int endIdx, double[] inreal, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_MAXINDEX(int startIdx, int endIdx, double[] inreal, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_MEDPRICE(int startIdx, int endIdx, double[] high, double[] low, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_MFI(int startIdx, int endIdx, double[] high, double[] low, double[] close, double[] volume, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_MIDPOINT(int startIdx, int endIdx, double[] inreal, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_MIDPRICE(int startIdx, int endIdx, double[] high, double[] low, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_MIN(int startIdx, int endIdx, double[] inreal, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_MININDEX(int startIdx, int endIdx, double[] inreal, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, int[] outInteger);
    int TA_MINMAX(int startIdx, int endIdx, double[] inreal, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outMin, double[] outMax);
    int TA_MINMAXINDEX(int startIdx, int endIdx, double[] inreal, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, int[] outMinIdx, int[] outMaxIdx);
    int TA_MINUS_DI(int startIdx, int endIdx, double[] high, double[] low, double[] close, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_MINUS_DM(int startIdx, int endIdx, double[] high, double[] low, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_MOM(int startIdx, int endIdx, double[] inreal, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_MULT(int startIdx, int endIdx, double[] inreal0, double[] inreal1, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_NATR(int startIdx, int endIdx, double[] high, double[] low, double[] close, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_OBV(int startIdx, int endIdx, double[] inreal, double[] volume, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_PLUS_DI(int startIdx, int endIdx, double[] high, double[] low, double[] close, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_PLUS_DM(int startIdx, int endIdx, double[] high, double[] low, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_PPO(int startIdx, int endIdx, double[] inreal, int optInFastPeriod, int optInSlowPeriod, int optInMAType, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_ROC(int startIdx, int endIdx, double[] inreal, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_ROCP(int startIdx, int endIdx, double[] inreal, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_ROCR(int startIdx, int endIdx, double[] inreal, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_ROCR100(int startIdx, int endIdx, double[] inreal, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_RSI(int startIdx, int endIdx, double[] inreal, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_SAR(int startIdx, int endIdx, double[] high, double[] low, double optInAccelerationFactor, double optInAFMaximum, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_SAREXT(int startIdx, int endIdx, double[] high, double[] low, double optInStartValue, double optInOffsetonReverse, double optInAFInitLong, double optInAFLong, double optInAFMaxLong, double optInAFInitShort, double optInAFShort, double optInAFMaxShort, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_SIN(int startIdx, int endIdx, double[] inreal, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_SINH(int startIdx, int endIdx, double[] inreal, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_SMA(int startIdx, int endIdx, double[] inreal, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_SQRT(int startIdx, int endIdx, double[] inreal, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_STDDEV(int startIdx, int endIdx, double[] inreal, int optInTimePeriod, double optInDeviations, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_STOCH(int startIdx, int endIdx, double[] high, double[] low, double[] close, int optInFastKPeriod, int optInSlowKPeriod, int optInSlowKMA, int optInSlowDPeriod, int optInSlowDMA, IntByReference outBegIdx, IntByReference outNBElement, double[] outSlowK, double[] outSlowD);
    int TA_STOCHF(int startIdx, int endIdx, double[] high, double[] low, double[] close, int optInFastKPeriod, int optInFastDPeriod, int optInFastDMA, IntByReference outBegIdx, IntByReference outNBElement, double[] outFastK, double[] outFastD);
    int TA_STOCHRSI(int startIdx, int endIdx, double[] inreal, int optInTimePeriod, int optInFastKPeriod, int optInFastDPeriod, int optInFastDMA, IntByReference outBegIdx, IntByReference outNBElement, double[] outFastK, double[] outFastD);
    int TA_SUB(int startIdx, int endIdx, double[] inreal0, double[] inreal1, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_SUM(int startIdx, int endIdx, double[] inreal, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_T3(int startIdx, int endIdx, double[] inreal, int optInTimePeriod, double optInVolumeFactor, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_TAN(int startIdx, int endIdx, double[] inreal, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_TANH(int startIdx, int endIdx, double[] inreal, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_TEMA(int startIdx, int endIdx, double[] inreal, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_TRANGE(int startIdx, int endIdx, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_TRIMA(int startIdx, int endIdx, double[] inreal, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_TRIX(int startIdx, int endIdx, double[] inreal, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_TSF(int startIdx, int endIdx, double[] inreal, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_TYPPRICE(int startIdx, int endIdx, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_ULTOSC(int startIdx, int endIdx, double[] high, double[] low, double[] close, int optInFirstPeriod, int optInSecondPeriod, int optInThirdPeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_VAR(int startIdx, int endIdx, double[] inreal, int optInTimePeriod, double optInDeviations, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_WCLPRICE(int startIdx, int endIdx, double[] high, double[] low, double[] close, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_WILLR(int startIdx, int endIdx, double[] high, double[] low, double[] close, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
    int TA_WMA(int startIdx, int endIdx, double[] inreal, int optInTimePeriod, IntByReference outBegIdx, IntByReference outNBElement, double[] outReal);
}